server:
#  port: 6546
  port: 1010

spring:
  datasource:
    url: jdbc:postgresql://31.134.130.194:8888/db-spring
#    url: jdbc:postgresql://192.168.1.4:5432/nw-db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://31.134.130.194:8888/db-spring
#    url: jdbc:postgresql://192.168.1.4:5432/nw-db
    user: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
application:
  security:
    access-token:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 1296000000
    refresh-token:
      expiration: 2592000000


springdoc:
  swagger-ui:
    path: /swagger-ui.html

